### ISSUE TITLE
machine.go::GetData() cache does not work

### ISSUE THREAD

**Issue by grayside** [phase2/rig#123]
The Machine.GetData method checks to see if one of it's internal properties (inspectData) has been initialized by a previous call to the method. If so, it will return that data instead of re-running `docker machine inspect`. However, despite effectively assigning the value from that execution and returning it, the value does persist as part of the machine struct to the next execution.

m.inspectData is always detected as `nil`.

### Troubleshooting

I modified the function so the entry reads as follows so I could quickly evaluate if caching works.

```
	if m.inspectData != nil {
		m.out.Info.Printf("Cached hit.")
		return m.inspectData
	} else {
		m.out.Info.Printf("Cache miss.")
	}
```

I have tried several blind approaches to get this working but cannot see the problem. Stackoverflow has not been helpful: this is a difficult problem to specifically phrase. Might be worth a new post.

### Benefits

Solving this problem will prevent a minor amount of redundant work, which translates to a couple hundred milliseconds here and there.

**Comment by febbraro** [comment]
Fix in #125
