### ISSUE TITLE
Increasing Docker machine's disk size

### ISSUE THREAD

**Issue by rob-p2** [phase2/rig#127]
For a particular project using multisites I ran out of disk space. 

I was unable to do a `rig start --disk-size 80000`

It just didn't seem to do anything.

Then I tried to replicate the actual command instead of the alias and got the same result.
`docker-machine create --virtualbox-disk-size 6000 -d virtualbox dev -D`

Reading up on the documentation I found the following:

`docker-machine create --virtualbox-disk-size 80000 --virtualbox-cpu-count 2 --virtualbox-memory 4096 -d virtualbox dev`

This one worked. Apparently -D is no longer a valid flag.

**Comment by febbraro** [comment]
Not sure where that -D comes from. There is nothing in the create command that uses a -D and nothing in the entire code base that is `-D`.

**Comment by febbraro** [comment]
If you run with `--verbose` (and are on version `2.0.0+` it will show every command that it throws to the system via exec

**Comment by grayside** [comment]
@rob-p2 did you first run `rig remove`? The flags such as disk capacity are only run when the machine is first created.

**Comment by rob-p2** [comment]
Yes, it worked very well.
