### ISSUE TITLE
Logic error on the standalone dashboard command

### ISSUE THREAD

**Issue by febbraro** [phase2/rig#132]
https://github.com/phase2/rig/blob/develop/commands/dashboard.go#L37

It should return success if the error is nil, currently on a successful launch of the dashboard it will report an error, but only if using the `rig dashboard` command directly as that is what is executed via `Run()`  when called via `rig start` that portion of code never gets executed.

**Comment by grayside** [comment]
Fixed by https://github.com/phase2/rig/pull/133
