### ISSUE TITLE
New spinner obfuscates password entry requests (e.g., for sudo ops)

### ISSUE THREAD

**Issue by grayside** [phase2/rig#134]
> I upgraded to rig 2.1.0 and just tried to stop my dev machine and thought it was borked on the second shut down step (Cleaning up local networking). I know it says "may require your admin password” but it’s not immediately clear that it’s asking for it when the cursor just changes to a key. A couple of our other colleagues also didn’t realize it was asking for a password. I thought my dev machine just wasn’t stopping. 

This may require special handling when a given command may stop to ask for sudo, unless we can preemptively escalate to admin permissions once when we know it will be needed for a given command.

**Comment by febbraro** [comment]
Should we file an issue here: https://github.com/slok/gospinner/issues ?

**Comment by grayside** [comment]
I think that would be good, but I expect it will be more of a support request. This problem is really difficult to search in the abstract. I can look at filing something.

I've been meaning to see what would happen if I dropped a tab character at the end of some or all messages, thats been my only brainstorm aside from aggressively managing the use of sudo as application state.

**Comment by grayside** [comment]
Adding a tab makes it minutely more clear, but does not seem good enough.

### Current behavior

<img width="307" alt="screen shot 2018-01-29 at 10 35 45 am" src="https://user-images.githubusercontent.com/283489/35527639-493f2a2e-04e0-11e8-863e-889e460700f0.png">

### With Tab Added

<img width="358" alt="screen shot 2018-01-29 at 10 35 53 am" src="https://user-images.githubusercontent.com/283489/35527646-4cb26ed2-04e0-11e8-874d-419625432c2a.png">
