### ISSUE TITLE
Limit rig watch to macOS

### ISSUE THREAD

**Issue by febbraro** [phase2/rig#19]
The watch command is currently only a Mac option. Ensure it can't be run on Windows/Linux.

**Comment by febbraro** [comment]
rig watch is now deprecated since `rig project sync:start` is rolling out soon.  We will need to ensure `project sync` works on windows (and it is not needed on Linux since there is no NFS/SSHFS/FUSE boundary.

**Comment by grayside** [comment]
So should we try to implement those or do we close it?

**Comment by febbraro** [comment]
Overcome by events. We won't implement this now that unison sync is in place.
