### ISSUE TITLE
Minimal Linux Version of rig

### ISSUE THREAD

**Issue by febbraro** [phase2/rig#21]
For things like DNS and Dashboard it would be good to have rig for those things to avoid common mistakes.  We could even have `rig dns --install` or something that would setup the systemd or upstart units to make it run on boot.

**Comment by grayside** [comment]
Is part of the idea of a minimal version that loading commands would be OS-adaptive?

**Comment by febbraro** [comment]
Yes, I think we would lod commands on Linux based on what would be possible/available to use. Then within the commands they would also work differently based on which OS. For example, within DNS, no need to setup routing rules on Linux, but we need it on Windows and Darwin.

**Comment by febbraro** [comment]
Also #99
