### ISSUE TITLE
Inconsistent handling of alias/command conflicts

### ISSUE THREAD

**Issue by grayside** [phase2/rig#37]
In our current pre-release we have `rig project create`. If we have a configured script with the alias `create`, the result is inconsistent:

* The built-in command is executed on `rig project create`
* The aliased help is displayed on `rig project help create`

Since this functionality is relying on the command controller implemented in https://github.com/urfave/cli, I think this needs an upstream fix.

**Comment by grayside** [comment]
Though per discussion and some of the ideas in #39 and #40, maybe we could validate the alias is non-conflicting and leave upstream to it's own devices.

**Comment by febbraro** [comment]
Resolved in #43
