### ISSUE TITLE
Configure a script key without any values causes a panic

### ISSUE THREAD

**Issue by grayside** [phase2/rig#39]
If you add a script definition to an outrigger.yml, such as:

```
scripts:
    awesome:
```
it kernel panics on running simple things like `rig project`. We should detect this state and output an error message indicating the broken configuration. Ideally this is something that would be part of a `rig project config` or `rig project validate` command.

Because I'm proposing an enhancement to fix an edge case bug, I've added both labels.

**Comment by febbraro** [comment]
Resolved in #43
