### ISSUE TITLE
Introduce indication of progress (e.g., spinners) and/or add more info logging

### ISSUE THREAD

**Issue by grayside** [phase2/rig#42]
Since converting much of the `rig start` output to verbose logs, the activities and timing for the process has come to feel much more mysterious.

I think it would benefit considerably from more "one-liners" around what it's doing, such as "Starting DNS services/Starting NFS services".

Furthermore, if we find it can be reliably presented, a progress meter to indicate how far the process has gone would help indicate whether it's hung or just taking 20 seconds. I found a couple progress meter libraries we could use in this case.

**Comment by grayside** [comment]
https://github.com/vbauerster/mpb

**Comment by febbraro** [comment]
I like the idea of a progress meter.

**Comment by grayside** [comment]
I gave this a try several days ago. The API for mpb was a bit confusing and I haven't got the numbers adding up yet. The biggest challenge is how long 1-2 of the operations are, it makes the progress bar look like it hangs as well.

**Comment by grayside** [comment]
After the previous attempt and thinking it over, most of our operations are not well-suited to progress meters. Progress meters are for quantifiable progress, which we really only have for the data-backup and data-restore jobs.

Instead, we have a desire to prove to users that their commands have not hung, even if there's a 20-60 second processing period (or more). That calls for spinners, of which there are a number of libraries.
