### ISSUE TITLE
Proposed timeout for "rig doctor"

### ISSUE THREAD

**Issue by danshumaker** [phase2/rig#48]
When my 
```bash
eval "$(rig config)"
```
was not evaluated or up to date, then the ```rig doctor``` command would stall or halt for more than 30 seconds.
After re-evaling the rig config,  the rig doctor command returns almost instantaneously (as it should).

This ticket/issue is a suggestion to put a quick timeout (say 5 seconds) on rig doctor and possibly an output message to "WARNING:timeout -- Please run eval $(rig config) and try again"... or something to that effect. (cause ya know,, better UX and all ;)

**Comment by grayside** [comment]
After thinking about it, this is either a bug to fix or the signs of a feature.

As a bug, a timeout and warning makes sense.
As a feature, `rig doctor` should as a first step see if those environment variables are set, and provide the guidance to run the eval command if it's missing.

**Comment by febbraro** [comment]
We can check for those variables, but they need to be set to usable values or you will still get the timeout. This happens from being pointed to a different machine as well as a clean env with no variables.

**Comment by grayside** [comment]
Can we compare the variables that are set with the values from the current machine? E.g., internally check the env against the data behind `rig config`?
