### ISSUE TITLE
Add ability to set a longer timeout on rig project sync:start

### ISSUE THREAD

**Issue by tekante** [phase2/rig#53]
For users with slow machines or very large project directories the `rig project sync:start` command may timeout before unison can finish the initial sync even though everything is working. The ability to optionally set a timeout length could be useful.

**Comment by grayside** [comment]
To confirm, it's unison that's timing out, right?

**Comment by tekante** [comment]
No, it's our waiting for the stuff to show up in the log file that's timing out and reporting that syncing isn't working when it just needs to wait longer.

**Comment by tekante** [comment]
Didn't mean to close, just meant to comment.

Basically there is a constant of 600 used in function WaitForSyncInit that needs to be configurable https://github.com/phase2/rig/blob/develop/cli/commands/project_sync.go#L210
