### ISSUE TITLE
Provide rig data filesystem functions

### ISSUE THREAD

**Issue by grayside** [phase2/rig#6]
On OSX, the docker-machine insulates the user from easily interacting with the /data directory which carries so much of the data used in containers. To help them understand it's there and interact with it, let's provide a `rig data` command.

1. This would probably wrap docker-machine scp/ssh
2. Is that a good idea?
3. Would we make it available as `rig data ls`/`rig data rm` or would we just do a less secured command passthru?

If we answer these questions all the way through, let's flip the label from question to enhancement.

**Comment by febbraro** [comment]
Are you imagining that this would be as a way to see which projects have "data" and ways to clear/create, etc.?   I'm not sure what benefit or what someone would want to accomplish with "data" commands.

**Comment by grayside** [comment]
Yes. I think there are times when ls, rm, and rsync of specific files or directories are useful, and it is often several weeks before developers start to digest the role of docker-machine as part of the stack.

If we expose a `rig data` command suite, we not only make more transparent this hidden data, we can use it as a teaching moment to point back to the docker-machine per #5.

**Comment by grayside** [comment]
This seems like it's sufficiently address with `rig ssh`, we can look at expanding on that after it gets some usage.
